name: qr_code_scanner_and_generator
description: A QR Code Scanner and QR Code Generator build using flutter.

publish_to: "none"

version: 2.0.2+2002

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  clipboard: ^0.1.3
  cupertino_icons: ^1.0.5
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  url_launcher: 6.1.12
  fluttertoast: 8.2.2
  widgets_to_image: ^0.0.2
  path_provider: ^2.0.15
  permission_handler: ^10.4.3
  share_plus: ^7.0.2

dev_dependencies:
  flutter_launcher_icons: 0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpeg"

  flutter_test:
    sdk: flutter

flutter:
  assets:
    - shorebird.yaml
  uses-material-design: true
